### ISSUE TITLE
Original Menu Exit option not working

### ISSUE THREAD

**Issue by peter4432** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#26]
> Decomp exe is the v3-windows-x64 verion from the sega forever huh #374 autobuild.
> Scripts used were downloaded from Cleanup branch on Oct 21st.
> Data Source = Sonic Origins

> GameType=0
> FullScreen=false
> Borderless=false
> VSync=false
> ScalingMode=0
> WindowScale=3
> ScreenWidth=424
> RefreshRate=60

When in the orginal menu, select the Exit Game option does not close the game, instead it goes back to the title screen starting with the Sega logo. The menu music also keeps playing until the Start screen appears, whe the expected title theme is started instead.

https://user-images.githubusercontent.com/7239300/197325742-d36a6581-8df7-4f41-abf8-ba85d48cbd26.mp4

Issue does not occur if data.rsdk or data folder from Steam version used.

**Comment by Rubberduckycooly** [comment]
That's how the mobile version behaves, however mobile version doesn't have an exit button so it's not noticeable. Issue is since pause menu exit and main menu exit share code that's toggled per-platform so running mobile code (scripts or any mobile rsdk) will enable mobile logic, even if menu is setup to use PC via the engine's platform id.
